language: node_js
node_js:
- '6'
env:
  global:
  - AWS_REGION=us-east-1
  - SLS_DEBUG=true
  - secure: jzXDK7YwQP8u9M2DyfeNHIwil7bmHRAPiMuK7R6enflRaBLcDH01YPIMkR5wvM+G2fzkuPxV/8Lyi7+LgPRFvnOHFN2923zfAtIhxLYNU3kKrosAwzoza1ZQpBCVLJgKQ/dtDL6u1gg3jX0QPJ8UsYzwvwA12sHVoHKq4ezqM+v2gAUCEZ9YQxQyMqEasLogMGJ+WCfS4xlgmTU1ft7tHDRQDDOAjBI5uPm5N/3OAmwP+lmAjMpFSB/AgSXeDvQ3oE5K0u4P1xaEDxQTrHHrlkHcB0C2EeWjKghuzrQ4hj20ynhE3zzyaEt8f270r+dPaoc67gXkqOtM175TJdZ9F03FiDQpH+Wy0hh0x51unYDT3XFe6VP1W37bkOqbyLDrsfFsLMi6ta6QDUWfFR83ztdJP3I273QgFqEEwG+nDQ5wyQK0QjJLM5qIcWCGNkF0yQSdeAsxVLfsjQ8/1etq534/OQz1Ype2MR8kf8DtP++gAfvL2aZ2tXyPvNJncKSlkG7T7N3xhq/irChAfY8OQUua3irzsceeacDKlueH+xugVfEu40y+4/7hW6xvTwx6Z6JDnku7fRk4z9EqZXCUQL++S5G7gsOz0HoLBSmjSEIIM/38T0ctfUDisH3jyUePgDDL/x//Xgdu0ZKr6ZjhK/t41Y2Tl9033GBGVZNAOBw=
  - secure: WVu2qD/caAifQrRRVZhxkhUR7vOilhz+4O+toUyfPkbOy49g42OYRvZC2fBtwXT86mLJXkJ3zsdLWzjoPwauyNw9Qko8GsfmdDPLiuuQcqSp80rRcsV3GaBT0QI1ZUbnlx/b6PS6EWpG64fV8K/xWltwvtq7W1aWabEfnAm3Dx9dzEHmC3Pgbcz7UC4tRebn/Va0n0WZe11ZTFS1kfdmwfNdjRDAAAOUgdONYvEXho9dmV/F2e9kgcZvDclPdHZoxuxmDYc1gzyc3fINLCIbs4kFTIlV0tqt9h/nRS1eumnmLPolxdATG15olT8Zk2zqr0h4QfnDq8JaRZEU3nq6ouw4uic8vtoijHemt/i57lVz/A4JmgfFQXi7QoODbsdxKtShuJzJVMChq5cPfFH/8gwZekpzijcqazE1z0ERbXatFMscr9dwpxxBBVz79q0HqXcVFcCbfU8W+w6erKHJqyT7ISMvRd9cDEGO4xng7Jpqf+wP6XrtqrkvULYW6qDx8aLwAtGnR9s3aCW+V5dtBOnKWudqCcY61OY3fWjDAQ6ZA8eBHZGHjm4fnhtU2lLhKtwGqJbsO7GHa41IPZLYqHEemQG5Prkz26GAOyQETyaxyIt8za4iGWn6K94iWL1SCwWa8JypO1xosuFhi6sVtFMe9wmjkRSpGgsuE20IV2c=
before_install:
- npm i -g serverless@1.4.0
script: "./deploy.sh"
