service: serverless-facebook-messenger-bot

provider:
  name: aws
  runtime: nodejs4.3
  region: us-east-1
  stage: nodeploy
  profile: feedbot
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"
  environment:
    FB_API_KEY: ${file(./_secrets.yml):fb_api_key}
    CHALLENGE_TOKEN: ${file(./_secrets.yml):fb_challenge_token}

functions:
  webhook:
    handler: handler.webhook
    events:
      - http:
          method: GET
          path: webhook
          integration: lambda
      - http:
          method: POST
          path: webhook
          integration: lambda

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable-${env:STAGE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
